# Generated by Django 2.2.2 on 2020-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('intern', models.CharField(max_length=80)),
            ],
        ),
    ]
